apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ffc-demo
  namespace: ffc-demo
spec:
  path: ./services/environments/${ENVIRONMENT}/01
  interval: 5m
  timeout: 3m
  prune: true
  sourceRef:
    kind: GitRepository
    name: ffc-app-repo
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      ACR_NAME: "sndcdoinfcr2401p"
      NAMESPACE: "ffc-demo"
