apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-base
  namespace: flux-system
spec:
  path: ./services/base
  interval: 15m
  timeout: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: ffc-app-repo
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      ACR_NAME: ${ACR_NAME}
      NAMESPACE: ${NAMESPACE}
