apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-base
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: ffc-app-repo
    namespace: flux-system
  interval: 2m
  timeout: 3m
  prune: true
  path: ./services/environments/${ENVIRONMENT}/01