apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ffc-demo
  namespace: ffc-demo
spec:
  path: ./services/base
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      ACR_NAME: ${ACR_NAME}
      NAMESPACE: ${NAMESPACE}
