apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  # name: apps-base
  # namespace: flux-system
  name: main
  namespace: flux-system
resources:
  # - ../../../base/kustomize.yaml
  - ../../../ffc-demo

patches:
  - path: kustomize.yaml
    target:
      kind: Kustomization