apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - ../../../ffc-demo/base/kustomize.yaml
  - ../../../ffc-demo/snd/01

patches:
  - path: kustomize.yaml
    target:
      kind: Kustomization