apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-snd-01-kustomization
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: ffc-app-repo
    namespace: flux-system
  interval: 2m
  prune: true
  postBuild:
    substitute:
      ENVIRONMENT: "snd"
      NAMESPACE: "ffc-demo"
      HELM_REPO_NAME: "sndcdoinfcr2401p"