apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: main
spec:
  path: ./services/environments/snd/01
  interval: 15m
  postBuild:
    substitute:
      ENVIRONMENT: "snd"
