apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: main
spec:
  path: ./services
  interval: 15m
  timeout: 10m
  postBuild:
    substitute:
      ENVIRONMENT: "snd"